### ISSUE TITLE
how to train model and i am getting error, i am using ububtu os

### ISSUE THREAD

**Issue by avinkr** [Animesh1911/Tomato-Leaf-Disease-Detection#1]

**Comment by Animesh1911** [comment]
I would suggest you to take a look at this link -
https://stackoverflow.com/questions/69819422/how-can-i-fix-cv2-error-opencv4-5-4-dev
This may help.

**Comment by avinkr** [comment]
still not getting please help me its very needed to me
 sir

**Comment by avinkr** [comment]
i am requesting you sir its very imp to me

**Comment by Animesh1911** [comment]
This may happen when the images are not loaded  correctly. I would suggest you to check the path once again.
