### ISSUE TITLE
file error let me know wer to add files

### ISSUE THREAD

**Issue by avinkr** [Animesh1911/Tomato-Leaf-Disease-Detection#2]

**Comment by Animesh1911** [comment]
It should be 'train/Tomato__Target_Spot.' (Note the capital S).
You just have to change the small s in the categories list in line 11 to a capital s.
I think while uploading I mistakingly typed 'Tomato__Target_spot'. Sorry for the incovenience.

This error occurs when you spell the names of folders or files incorrectly.

**Comment by Animesh1911** [comment]
I have made the changes in the code in Github.

Thank you for pointing out thhe error.
